[project]
name = "open_aglabs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "geopandas>=1.1.1",
    "jupyter>=1.1.1",
    "pandas>=2.0.0",
    "pydantic>=2.11.9",
    "pytest>=8.4.2",
    "shapely>=2.1.1",
]
